browser=chrome
url=https://automationexercise.com/
implicit.wait=10
valid.email=kishorejk112@gmail.com
valid.password=TestPassword@123
explicit.wait=15
invalid.email=kishore123@gmail.com
invalid.password=Wrong@123
valid.username=kishore